//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonContract
    {
        public int CommonContractID { get; set; }
        public Nullable<int> Acquirer { get; set; }
        public Nullable<int> Seller { get; set; }
        public Nullable<int> DealType { get; set; }
        public System.DateTime ContractDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Realty { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual DealType DealType1 { get; set; }
        public virtual Realty Realty1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
