//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceContract
    {
        public int ServiceContractID { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> DealType { get; set; }
        public System.DateTime ContractDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual DealType DealType1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
